try:
    print(5)
except Exception as e:
    print(e)
